[build]
builder = "dockerfile"
dockerfilePath = "packages/api/Dockerfile"
watchPatterns = ["packages/api/**", "packages/core/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
